# **StresID: a multimodal dataset for Stress Detection**

### **Basic EDA on existance dataset**
- self_assessments.csv
- demographics.csv

In [ ]:
# !pip install numpy pandas matplotlib seaborn plotly openpyxl -q

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip

In [16]:
# Import required libraries
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from pathlib import Path

In [32]:
# Read and Load dataset
self_assessment = pd.read_csv('data/self_assessments.csv', sep=';', header=0)
demographics = pd.read_csv('data/demographics.csv', sep=';')
print("Self Assessment Dataset:")
print(self_assessment.head())
print(self_assessment.tail())
print("\nDemographics Dataset:")
print(demographics.head())

Self Assessment Dataset:
               Tasks hh2e wfsl 37ir hvpa ql3b r0a3 qx2o wssm ctzy  ... y8c3  \
0    Breathing_relax    6    6    9    9   10   10    9    8    9  ...    9
1   Breathing_stress    5    4    2    1    1    0    2    0    0  ...    1
2  Breathing_valence  NaN    8    5    7    5    8    8    6    7  ...    5
3  Breathing_arousal  NaN    3    3    8    2    1    2    1    7  ...    7
4       Video1_relax    8    6    3    7   10   10    9    5    4  ...    8

  g7r2 f6q3 e5p4 d4n6 c3m7 b2l8 a1k9 t6v9 b9w0
0    8    9   10    5    4    8    7    5    8
1    0    1    3    2    6    1    5    5    2
2    7    7    8    5    8    7    6    6    7
3    5    1    3    4    7    8    8    3    8
4    8    9    8    2    2    2    7    7    5

[5 rows x 66 columns]
             Tasks       hh2e       wfsl      37ir     hvpa      ql3b  \
40     Relax_relax          6        NaN         7        6        10
41    Relax_stress          6        NaN         1        2         0
42   Relax_valence        NaN        NaN         7        6         8
43   Relax_arousal        NaN        NaN         6        5         8
44  Most_stressful  Counting2  Counting2  Speaking  Reading  Speaking

         r0a3      qx2o      wssm  ctzy  ...       y8c3       g7r2    f6q3  \
40         10         4         7     9  ...          9          8       9
41          1         5         0     1  ...          0          0       1
42          6         5         7     5  ...          6          5       8
43          2         3         0     1  ...          4          2       1
44  Counting3  Speaking  Speaking  Math  ...  Counting2  Counting3  Stroop

         e5p4       d4n6    c3m7       b2l8       a1k9       t6v9       b9w0
40          8          5       7          6          8          3          2
41          2          3       5          5          3          3          5
42          7          5       6          7          8          5          5
43          3          3       7          6          5          0          4
44  Counting2  Counting1  Stroop  Counting2  Counting2  Counting2  Counting2

[5 rows x 66 columns]

Demographics Dataset:
  Subject   Age Gender
0    8g4y  24.0      M
1    qw5t  25.0      F
2    h8r2  26.0      M
3    2z7d  24.0      M
4    j9h8  26.0      M

In [19]:
# # Load and transpose self_assessment dataset
# df = pd.read_csv('data/self_assessments.csv', sep=';', index_col='Tasks').T
# df.index.name = 'Instance'
# df.to_csv('self_assessments_transposed.csv')

# print(df.head())
# print(f"\nShape: {df.shape}")

### **Preprocessing**

In [33]:
# Remove the last row from self_assessment dataset
self_assessment = self_assessment[:-1]
# print("\nUpdated Self Assessment Dataset:")
# print(self_assessment.tail())

# Store the column names of self_assessment dataset in 'subjects'
subjects = self_assessment.columns[1:]

# Converts the data in "subjects" into fload
self_assessment[subjects] = self_assessment[subjects].astype(float)
print("\nData types of self_assessment dataset:")
self_assessment.tail()

Data types of self_assessment dataset:

,Tasks,hh2e,wfsl,37ir,hvpa,ql3b,r0a3,qx2o,wssm,ctzy,...,y8c3,g7r2,f6q3,e5p4,d4n6,c3m7,b2l8,a1k9,t6v9,b9w0
39,Counting3_arousal,NaN,6.0,8.0,8.0,10.0,6.0,6.0,6.0,9.0,...,5.0,4.0,3.0,5.0,6.0,5.0,6.0,7.0,8.0,8.0
40,Relax_relax,6.0,NaN,7.0,6.0,10.0,10.0,4.0,7.0,9.0,...,9.0,8.0,9.0,8.0,5.0,7.0,6.0,8.0,3.0,2.0
41,Relax_stress,6.0,NaN,1.0,2.0,0.0,1.0,5.0,0.0,1.0,...,0.0,0.0,1.0,2.0,3.0,5.0,5.0,3.0,3.0,5.0
42,Relax_valence,NaN,NaN,7.0,6.0,8.0,6.0,5.0,7.0,5.0,...,6.0,5.0,8.0,7.0,5.0,6.0,7.0,8.0,5.0,5.0
43,Relax_arousal,NaN,NaN,6.0,5.0,8.0,2.0,3.0,0.0,1.0,...,4.0,2.0,1.0,3.0,3.0,7.0,6.0,5.0,0.0,4.0

In [50]:
# Organize and filter data based on combinations of subjects and tasks

# Define tasks
tasks = ["Breathing", "Video1", "Video2", "Counting1", "Counting2", 
         "Stroop", "Math", "Speaking", "Reading", "Counting3", "Relax"]

# Creating the Unique Keys to pair up every single subject with every single task
unique_keys = [f"{subject}_{task}" for subject in subjects for task in tasks]
# print("\nUnique Keys for Subject-Task Combinations:")
# print(unique_keys)

# Creates a dictionary with the keys combinations, and all the values are initially set to None
labels_Dict = dict.fromkeys(unique_keys)
print("\nInitial Labels Dictionary with Unique Keys:")
print(labels_Dict)

# Loop through each subject and task to populate the labels_Dict with the corresponding values from the self_assessment dataset
for label in unique_keys:
    subject, task = label.split('_')[0], label.split('_')[1]
    labels_Dict[label] = list(self_assessment[self_assessment['Tasks'].str.contains(task)][subject])

labels = pd.DataFrame(labels_Dict)
labels.index = ['relax', 'stress', 'valence', 'arousal']
print("\nLabels DataFrame with Subject-Task Combinations:")
labels.head()

Initial Labels Dictionary with Unique Keys:
{'hh2e_Breathing': None, 'hh2e_Video1': None, 'hh2e_Video2': None, 'hh2e_Counting1': None, 'hh2e_Counting2': None, 'hh2e_Stroop': None, 'hh2e_Math': None, 'hh2e_Speaking': None, 'hh2e_Reading': None, 'hh2e_Counting3': None, 'hh2e_Relax': None, 'wfsl_Breathing': None, 'wfsl_Video1': None, 'wfsl_Video2': None, 'wfsl_Counting1': None, 'wfsl_Counting2': None, 'wfsl_Stroop': None, 'wfsl_Math': None, 'wfsl_Speaking': None, 'wfsl_Reading': None, 'wfsl_Counting3': None, 'wfsl_Relax': None, '37ir_Breathing': None, '37ir_Video1': None, '37ir_Video2': None, '37ir_Counting1': None, '37ir_Counting2': None, '37ir_Stroop': None, '37ir_Math': None, '37ir_Speaking': None, '37ir_Reading': None, '37ir_Counting3': None, '37ir_Relax': None, 'hvpa_Breathing': None, 'hvpa_Video1': None, 'hvpa_Video2': None, 'hvpa_Counting1': None, 'hvpa_Counting2': None, 'hvpa_Stroop': None, 'hvpa_Math': None, 'hvpa_Speaking': None, 'hvpa_Reading': None, 'hvpa_Counting3': None, 'hvpa_Relax': None, 'ql3b_Breathing': None, 'ql3b_Video1': None, 'ql3b_Video2': None, 'ql3b_Counting1': None, 'ql3b_Counting2': None, 'ql3b_Stroop': None, 'ql3b_Math': None, 'ql3b_Speaking': None, 'ql3b_Reading': None, 'ql3b_Counting3': None, 'ql3b_Relax': None, 'r0a3_Breathing': None, 'r0a3_Video1': None, 'r0a3_Video2': None, 'r0a3_Counting1': None, 'r0a3_Counting2': None, 'r0a3_Stroop': None, 'r0a3_Math': None, 'r0a3_Speaking': None, 'r0a3_Reading': None, 'r0a3_Counting3': None, 'r0a3_Relax': None, 'qx2o_Breathing': None, 'qx2o_Video1': None, 'qx2o_Video2': None, 'qx2o_Counting1': None, 'qx2o_Counting2': None, 'qx2o_Stroop': None, 'qx2o_Math': None, 'qx2o_Speaking': None, 'qx2o_Reading': None, 'qx2o_Counting3': None, 'qx2o_Relax': None, 'wssm_Breathing': None, 'wssm_Video1': None, 'wssm_Video2': None, 'wssm_Counting1': None, 'wssm_Counting2': None, 'wssm_Stroop': None, 'wssm_Math': None, 'wssm_Speaking': None, 'wssm_Reading': None, 'wssm_Counting3': None, 'wssm_Relax': None, 'ctzy_Breathing': None, 'ctzy_Video1': None, 'ctzy_Video2': None, 'ctzy_Counting1': None, 'ctzy_Counting2': None, 'ctzy_Stroop': None, 'ctzy_Math': None, 'ctzy_Speaking': None, 'ctzy_Reading': None, 'ctzy_Counting3': None, 'ctzy_Relax': None, 'uyrl_Breathing': None, 'uyrl_Video1': None, 'uyrl_Video2': None, 'uyrl_Counting1': None, 'uyrl_Counting2': None, 'uyrl_Stroop': None, 'uyrl_Math': None, 'uyrl_Speaking': None, 'uyrl_Reading': None, 'uyrl_Counting3': None, 'uyrl_Relax': None, 'v8mh_Breathing': None, 'v8mh_Video1': None, 'v8mh_Video2': None, 'v8mh_Counting1': None, 'v8mh_Counting2': None, 'v8mh_Stroop': None, 'v8mh_Math': None, 'v8mh_Speaking': None, 'v8mh_Reading': None, 'v8mh_Counting3': None, 'v8mh_Relax': None, '45lx_Breathing': None, '45lx_Video1': None, '45lx_Video2': None, '45lx_Counting1': None, '45lx_Counting2': None, '45lx_Stroop': None, '45lx_Math': None, '45lx_Speaking': None, '45lx_Reading': None, '45lx_Counting3': None, '45lx_Relax': None, 'r3zm_Breathing': None, 'r3zm_Video1': None, 'r3zm_Video2': None, 'r3zm_Counting1': None, 'r3zm_Counting2': None, 'r3zm_Stroop': None, 'r3zm_Math': None, 'r3zm_Speaking': None, 'r3zm_Reading': None, 'r3zm_Counting3': None, 'r3zm_Relax': None, '2hpu_Breathing': None, '2hpu_Video1': None, '2hpu_Video2': None, '2hpu_Counting1': None, '2hpu_Counting2': None, '2hpu_Stroop': None, '2hpu_Math': None, '2hpu_Speaking': None, '2hpu_Reading': None, '2hpu_Counting3': None, '2hpu_Relax': None, '4woj_Breathing': None, '4woj_Video1': None, '4woj_Video2': None, '4woj_Counting1': None, '4woj_Counting2': None, '4woj_Stroop': None, '4woj_Math': None, '4woj_Speaking': None, '4woj_Reading': None, '4woj_Counting3': None, '4woj_Relax': None, 'cxj0_Breathing': None, 'cxj0_Video1': None, 'cxj0_Video2': None, 'cxj0_Counting1': None, 'cxj0_Counting2': None, 'cxj0_Stroop': None, 'cxj0_Math': None, 'cxj0_Speaking': None, 'cxj0_Reading': None, 'cxj0_Counting3': None, 'cxj0_Relax': None, 'tmvd_Breathing': None, 'tmvd_Video1': None, 'tmvd_Video2': None, 'tmvd_Counting1': None, 'tmvd_Counting2': None, 'tmvd_Stroop': None, 'tmvd_Math': None, 'tmvd_Speaking': None, 'tmvd_Reading': None, 'tmvd_Counting3': None, 'tmvd_Relax': None, '2ea4_Breathing': None, '2ea4_Video1': None, '2ea4_Video2': None, '2ea4_Counting1': None, '2ea4_Counting2': None, '2ea4_Stroop': None, '2ea4_Math': None, '2ea4_Speaking': None, '2ea4_Reading': None, '2ea4_Counting3': None, '2ea4_Relax': None, '71i5_Breathing': None, '71i5_Video1': None, '71i5_Video2': None, '71i5_Counting1': None, '71i5_Counting2': None, '71i5_Stroop': None, '71i5_Math': None, '71i5_Speaking': None, '71i5_Reading': None, '71i5_Counting3': None, '71i5_Relax': None, 'kkf5_Breathing': None, 'kkf5_Video1': None, 'kkf5_Video2': None, 'kkf5_Counting1': None, 'kkf5_Counting2': None, 'kkf5_Stroop': None, 'kkf5_Math': None, 'kkf5_Speaking': None, 'kkf5_Reading': None, 'kkf5_Counting3': None, 'kkf5_Relax': None, 'uymz_Breathing': None, 'uymz_Video1': None, 'uymz_Video2': None, 'uymz_Counting1': None, 'uymz_Counting2': None, 'uymz_Stroop': None, 'uymz_Math': None, 'uymz_Speaking': None, 'uymz_Reading': None, 'uymz_Counting3': None, 'uymz_Relax': None, 'iqyg_Breathing': None, 'iqyg_Video1': None, 'iqyg_Video2': None, 'iqyg_Counting1': None, 'iqyg_Counting2': None, 'iqyg_Stroop': None, 'iqyg_Math': None, 'iqyg_Speaking': None, 'iqyg_Reading': None, 'iqyg_Counting3': None, 'iqyg_Relax': None, '9txq_Breathing': None, '9txq_Video1': None, '9txq_Video2': None, '9txq_Counting1': None, '9txq_Counting2': None, '9txq_Stroop': None, '9txq_Math': None, '9txq_Speaking': None, '9txq_Reading': None, '9txq_Counting3': None, '9txq_Relax': None, 'kycf_Breathing': None, 'kycf_Video1': None, 'kycf_Video2': None, 'kycf_Counting1': None, 'kycf_Counting2': None, 'kycf_Stroop': None, 'kycf_Math': None, 'kycf_Speaking': None, 'kycf_Reading': None, 'kycf_Counting3': None, 'kycf_Relax': None, 'k67g_Breathing': None, 'k67g_Video1': None, 'k67g_Video2': None, 'k67g_Counting1': None, 'k67g_Counting2': None, 'k67g_Stroop': None, 'k67g_Math': None, 'k67g_Speaking': None, 'k67g_Reading': None, 'k67g_Counting3': None, 'k67g_Relax': None, 'chdf_Breathing': None, 'chdf_Video1': None, 'chdf_Video2': None, 'chdf_Counting1': None, 'chdf_Counting2': None, 'chdf_Stroop': None, 'chdf_Math': None, 'chdf_Speaking': None, 'chdf_Reading': None, 'chdf_Counting3': None, 'chdf_Relax': None, 'bfl5_Breathing': None, 'bfl5_Video1': None, 'bfl5_Video2': None, 'bfl5_Counting1': None, 'bfl5_Counting2': None, 'bfl5_Stroop': None, 'bfl5_Math': None, 'bfl5_Speaking': None, 'bfl5_Reading': None, 'bfl5_Counting3': None, 'bfl5_Relax': None, 'dmbd_Breathing': None, 'dmbd_Video1': None, 'dmbd_Video2': None, 'dmbd_Counting1': None, 'dmbd_Counting2': None, 'dmbd_Stroop': None, 'dmbd_Math': None, 'dmbd_Speaking': None, 'dmbd_Reading': None, 'dmbd_Counting3': None, 'dmbd_Relax': None, '8g4y_Breathing': None, '8g4y_Video1': None, '8g4y_Video2': None, '8g4y_Counting1': None, '8g4y_Counting2': None, '8g4y_Stroop': None, '8g4y_Math': None, '8g4y_Speaking': None, '8g4y_Reading': None, '8g4y_Counting3': None, '8g4y_Relax': None, 'qw5t_Breathing': None, 'qw5t_Video1': None, 'qw5t_Video2': None, 'qw5t_Counting1': None, 'qw5t_Counting2': None, 'qw5t_Stroop': None, 'qw5t_Math': None, 'qw5t_Speaking': None, 'qw5t_Reading': None, 'qw5t_Counting3': None, 'qw5t_Relax': None, 'h8r2_Breathing': None, 'h8r2_Video1': None, 'h8r2_Video2': None, 'h8r2_Counting1': None, 'h8r2_Counting2': None, 'h8r2_Stroop': None, 'h8r2_Math': None, 'h8r2_Speaking': None, 'h8r2_Reading': None, 'h8r2_Counting3': None, 'h8r2_Relax': None, '2z7d_Breathing': None, '2z7d_Video1': None, '2z7d_Video2': None, '2z7d_Counting1': None, '2z7d_Counting2': None, '2z7d_Stroop': None, '2z7d_Math': None, '2z7d_Speaking': None, '2z7d_Reading': None, '2z7d_Counting3': None, '2z7d_Relax': None, 'j9h8_Breathing': None, 'j9h8_Video1': None, 'j9h8_Video2': None, 'j9h8_Counting1': None, 'j9h8_Counting2': None, 'j9h8_Stroop': None, 'j9h8_Math': None, 'j9h8_Speaking': None, 'j9h8_Reading': None, 'j9h8_Counting3': None, 'j9h8_Relax': None, '9t6n_Breathing': None, '9t6n_Video1': None, '9t6n_Video2': None, '9t6n_Counting1': None, '9t6n_Counting2': None, '9t6n_Stroop': None, '9t6n_Math': None, '9t6n_Speaking': None, '9t6n_Reading': None, '9t6n_Counting3': None, '9t6n_Relax': None, 'u3v9_Breathing': None, 'u3v9_Video1': None, 'u3v9_Video2': None, 'u3v9_Counting1': None, 'u3v9_Counting2': None, 'u3v9_Stroop': None, 'u3v9_Math': None, 'u3v9_Speaking': None, 'u3v9_Reading': None, 'u3v9_Counting3': None, 'u3v9_Relax': None, 'w2t5_Breathing': None, 'w2t5_Video1': None, 'w2t5_Video2': None, 'w2t5_Counting1': None, 'w2t5_Counting2': None, 'w2t5_Stroop': None, 'w2t5_Math': None, 'w2t5_Speaking': None, 'w2t5_Reading': None, 'w2t5_Counting3': None, 'w2t5_Relax': None, '7m3c_Breathing': None, '7m3c_Video1': None, '7m3c_Video2': None, '7m3c_Counting1': None, '7m3c_Counting2': None, '7m3c_Stroop': None, '7m3c_Math': None, '7m3c_Speaking': None, '7m3c_Reading': None, '7m3c_Counting3': None, '7m3c_Relax': None, '6k5f_Breathing': None, '6k5f_Video1': None, '6k5f_Video2': None, '6k5f_Counting1': None, '6k5f_Counting2': None, '6k5f_Stroop': None, '6k5f_Math': None, '6k5f_Speaking': None, '6k5f_Reading': None, '6k5f_Counting3': None, '6k5f_Relax': None, 'x1q3_Breathing': None, 'x1q3_Video1': None, 'x1q3_Video2': None, 'x1q3_Counting1': None, 'x1q3_Counting2': None, 'x1q3_Stroop': None, 'x1q3_Math': None, 'x1q3_Speaking': None, 'x1q3_Reading': None, 'x1q3_Counting3': None, 'x1q3_Relax': None, 'r5s8_Breathing': None, 'r5s8_Video1': None, 'r5s8_Video2': None, 'r5s8_Counting1': None, 'r5s8_Counting2': None, 'r5s8_Stroop': None, 'r5s8_Math': None, 'r5s8_Speaking': None, 'r5s8_Reading': None, 'r5s8_Counting3': None, 'r5s8_Relax': None, 'y9z6_Breathing': None, 'y9z6_Video1': None, 'y9z6_Video2': None, 'y9z6_Counting1': None, 'y9z6_Counting2': None, 'y9z6_Stroop': None, 'y9z6_Math': None, 'y9z6_Speaking': None, 'y9z6_Reading': None, 'y9z6_Counting3': None, 'y9z6_Relax': None, '4e8r_Breathing': None, '4e8r_Video1': None, '4e8r_Video2': None, '4e8r_Counting1': None, '4e8r_Counting2': None, '4e8r_Stroop': None, '4e8r_Math': None, '4e8r_Speaking': None, '4e8r_Reading': None, '4e8r_Counting3': None, '4e8r_Relax': None, '5f7t_Breathing': None, '5f7t_Video1': None, '5f7t_Video2': None, '5f7t_Counting1': None, '5f7t_Counting2': None, '5f7t_Stroop': None, '5f7t_Math': None, '5f7t_Speaking': None, '5f7t_Reading': None, '5f7t_Counting3': None, '5f7t_Relax': None, 'k2v7_Breathing': None, 'k2v7_Video1': None, 'k2v7_Video2': None, 'k2v7_Counting1': None, 'k2v7_Counting2': None, 'k2v7_Stroop': None, 'k2v7_Math': None, 'k2v7_Speaking': None, 'k2v7_Reading': None, 'k2v7_Counting3': None, 'k2v7_Relax': None, '6g6y_Breathing': None, '6g6y_Video1': None, '6g6y_Video2': None, '6g6y_Counting1': None, '6g6y_Counting2': None, '6g6y_Stroop': None, '6g6y_Math': None, '6g6y_Speaking': None, '6g6y_Reading': None, '6g6y_Counting3': None, '6g6y_Relax': None, '9j3o_Breathing': None, '9j3o_Video1': None, '9j3o_Video2': None, '9j3o_Counting1': None, '9j3o_Counting2': None, '9j3o_Stroop': None, '9j3o_Math': None, '9j3o_Speaking': None, '9j3o_Reading': None, '9j3o_Counting3': None, '9j3o_Relax': None, '8i4i_Breathing': None, '8i4i_Video1': None, '8i4i_Video2': None, '8i4i_Counting1': None, '8i4i_Counting2': None, '8i4i_Stroop': None, '8i4i_Math': None, '8i4i_Speaking': None, '8i4i_Reading': None, '8i4i_Counting3': None, '8i4i_Relax': None, '7h5u_Breathing': None, '7h5u_Video1': None, '7h5u_Video2': None, '7h5u_Counting1': None, '7h5u_Counting2': None, '7h5u_Stroop': None, '7h5u_Math': None, '7h5u_Speaking': None, '7h5u_Reading': None, '7h5u_Counting3': None, '7h5u_Relax': None, 'h8s1_Breathing': None, 'h8s1_Video1': None, 'h8s1_Video2': None, 'h8s1_Counting1': None, 'h8s1_Counting2': None, 'h8s1_Stroop': None, 'h8s1_Math': None, 'h8s1_Speaking': None, 'h8s1_Reading': None, 'h8s1_Counting3': None, 'h8s1_Relax': None, 'i9t9_Breathing': None, 'i9t9_Video1': None, 'i9t9_Video2': None, 'i9t9_Counting1': None, 'i9t9_Counting2': None, 'i9t9_Stroop': None, 'i9t9_Math': None, 'i9t9_Speaking': None, 'i9t9_Reading': None, 'i9t9_Counting3': None, 'i9t9_Relax': None, 'j1u8_Breathing': None, 'j1u8_Video1': None, 'j1u8_Video2': None, 'j1u8_Counting1': None, 'j1u8_Counting2': None, 'j1u8_Stroop': None, 'j1u8_Math': None, 'j1u8_Speaking': None, 'j1u8_Reading': None, 'j1u8_Counting3': None, 'j1u8_Relax': None, 'm8g5_Breathing': None, 'm8g5_Video1': None, 'm8g5_Video2': None, 'm8g5_Counting1': None, 'm8g5_Counting2': None, 'm8g5_Stroop': None, 'm8g5_Math': None, 'm8g5_Speaking': None, 'm8g5_Reading': None, 'm8g5_Counting3': None, 'm8g5_Relax': None, 'p9i3_Breathing': None, 'p9i3_Video1': None, 'p9i3_Video2': None, 'p9i3_Counting1': None, 'p9i3_Counting2': None, 'p9i3_Stroop': None, 'p9i3_Math': None, 'p9i3_Speaking': None, 'p9i3_Reading': None, 'p9i3_Counting3': None, 'p9i3_Relax': None, 'g9j5_Breathing': None, 'g9j5_Video1': None, 'g9j5_Video2': None, 'g9j5_Counting1': None, 'g9j5_Counting2': None, 'g9j5_Stroop': None, 'g9j5_Math': None, 'g9j5_Speaking': None, 'g9j5_Reading': None, 'g9j5_Counting3': None, 'g9j5_Relax': None, 'h7j3_Breathing': None, 'h7j3_Video1': None, 'h7j3_Video2': None, 'h7j3_Counting1': None, 'h7j3_Counting2': None, 'h7j3_Stroop': None, 'h7j3_Math': None, 'h7j3_Speaking': None, 'h7j3_Reading': None, 'h7j3_Counting3': None, 'h7j3_Relax': None, 'y8c3_Breathing': None, 'y8c3_Video1': None, 'y8c3_Video2': None, 'y8c3_Counting1': None, 'y8c3_Counting2': None, 'y8c3_Stroop': None, 'y8c3_Math': None, 'y8c3_Speaking': None, 'y8c3_Reading': None, 'y8c3_Counting3': None, 'y8c3_Relax': None, 'g7r2_Breathing': None, 'g7r2_Video1': None, 'g7r2_Video2': None, 'g7r2_Counting1': None, 'g7r2_Counting2': None, 'g7r2_Stroop': None, 'g7r2_Math': None, 'g7r2_Speaking': None, 'g7r2_Reading': None, 'g7r2_Counting3': None, 'g7r2_Relax': None, 'f6q3_Breathing': None, 'f6q3_Video1': None, 'f6q3_Video2': None, 'f6q3_Counting1': None, 'f6q3_Counting2': None, 'f6q3_Stroop': None, 'f6q3_Math': None, 'f6q3_Speaking': None, 'f6q3_Reading': None, 'f6q3_Counting3': None, 'f6q3_Relax': None, 'e5p4_Breathing': None, 'e5p4_Video1': None, 'e5p4_Video2': None, 'e5p4_Counting1': None, 'e5p4_Counting2': None, 'e5p4_Stroop': None, 'e5p4_Math': None, 'e5p4_Speaking': None, 'e5p4_Reading': None, 'e5p4_Counting3': None, 'e5p4_Relax': None, 'd4n6_Breathing': None, 'd4n6_Video1': None, 'd4n6_Video2': None, 'd4n6_Counting1': None, 'd4n6_Counting2': None, 'd4n6_Stroop': None, 'd4n6_Math': None, 'd4n6_Speaking': None, 'd4n6_Reading': None, 'd4n6_Counting3': None, 'd4n6_Relax': None, 'c3m7_Breathing': None, 'c3m7_Video1': None, 'c3m7_Video2': None, 'c3m7_Counting1': None, 'c3m7_Counting2': None, 'c3m7_Stroop': None, 'c3m7_Math': None, 'c3m7_Speaking': None, 'c3m7_Reading': None, 'c3m7_Counting3': None, 'c3m7_Relax': None, 'b2l8_Breathing': None, 'b2l8_Video1': None, 'b2l8_Video2': None, 'b2l8_Counting1': None, 'b2l8_Counting2': None, 'b2l8_Stroop': None, 'b2l8_Math': None, 'b2l8_Speaking': None, 'b2l8_Reading': None, 'b2l8_Counting3': None, 'b2l8_Relax': None, 'a1k9_Breathing': None, 'a1k9_Video1': None, 'a1k9_Video2': None, 'a1k9_Counting1': None, 'a1k9_Counting2': None, 'a1k9_Stroop': None, 'a1k9_Math': None, 'a1k9_Speaking': None, 'a1k9_Reading': None, 'a1k9_Counting3': None, 'a1k9_Relax': None, 't6v9_Breathing': None, 't6v9_Video1': None, 't6v9_Video2': None, 't6v9_Counting1': None, 't6v9_Counting2': None, 't6v9_Stroop': None, 't6v9_Math': None, 't6v9_Speaking': None, 't6v9_Reading': None, 't6v9_Counting3': None, 't6v9_Relax': None, 'b9w0_Breathing': None, 'b9w0_Video1': None, 'b9w0_Video2': None, 'b9w0_Counting1': None, 'b9w0_Counting2': None, 'b9w0_Stroop': None, 'b9w0_Math': None, 'b9w0_Speaking': None, 'b9w0_Reading': None, 'b9w0_Counting3': None, 'b9w0_Relax': None}

Labels DataFrame with Subject-Task Combinations:

,hh2e_Breathing,hh2e_Video1,hh2e_Video2,hh2e_Counting1,hh2e_Counting2,hh2e_Stroop,hh2e_Math,hh2e_Speaking,hh2e_Reading,hh2e_Counting3,...,b9w0_Video1,b9w0_Video2,b9w0_Counting1,b9w0_Counting2,b9w0_Stroop,b9w0_Math,b9w0_Speaking,b9w0_Reading,b9w0_Counting3,b9w0_Relax
relax,6.0,8.0,7.0,6.0,3.0,6.0,5.0,6.0,8.0,5.0,...,5.0,4.0,3.0,1.0,3.0,3.0,2.0,2.0,1.0,2.0
stress,5.0,2.0,3.0,5.0,7.0,6.0,6.0,6.0,4.0,7.0,...,2.0,3.0,4.0,6.0,6.0,6.0,7.0,6.0,7.0,5.0
valence,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,5.0,5.0,3.0,4.0,5.0,4.0,5.0,5.0,5.0
arousal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.0,7.0,9.0,9.0,9.0,9.0,9.0,5.0,8.0,4.0