## **Create Labels Using self_assessments.csv dataset**
**Create binary stress and 3-class stress lables using self_assessments dataset**

In [164]:
import os
import pandas as pd
import numpy as np

In [165]:
# read and lod self_assessments.csv dataset
self_assessments = pd.read_csv("data/self_assessments.csv", sep = ";", header = 0, index_col = 0)
print(self_assessments.info())

print("=" *50)
self_assessments.head()

<class 'pandas.DataFrame'>
Index: 45 entries, Breathing_relax to Most_stressful
Data columns (total 65 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   hh2e    23 non-null     str
 1   wfsl    41 non-null     str
 2   37ir    45 non-null     str
 3   hvpa    45 non-null     str
 4   ql3b    45 non-null     str
 5   r0a3    45 non-null     str
 6   qx2o    45 non-null     str
 7   wssm    45 non-null     str
 8   ctzy    45 non-null     str
 9   uyrl    45 non-null     str
 10  v8mh    45 non-null     str
 11  45lx    45 non-null     str
 12  r3zm    45 non-null     str
 13  2hpu    45 non-null     str
 14  4woj    45 non-null     str
 15  cxj0    45 non-null     str
 16  tmvd    45 non-null     str
 17  2ea4    45 non-null     str
 18  71i5    45 non-null     str
 19  kkf5    45 non-null     str
 20  uymz    45 non-null     str
 21  iqyg    45 non-null     str
 22  9txq    45 non-null     str
 23  kycf    45 non-null     str
 24  k67g    45 non-null     str
 25  chdf    45 non-null     str
 26  bfl5    45 non-null     str
 27  dmbd    45 non-null     str
 28  8g4y    45 non-null     str
 29  qw5t    45 non-null     str
 30  h8r2    45 non-null     str
 31  2z7d    45 non-null     str
 32  j9h8    45 non-null     str
 33  9t6n    45 non-null     str
 34  u3v9    45 non-null     str
 35  w2t5    45 non-null     str
 36  7m3c    45 non-null     str
 37  6k5f    45 non-null     str
 38  x1q3    45 non-null     str
 39  r5s8    45 non-null     str
 40  y9z6    45 non-null     str
 41  4e8r    45 non-null     str
 42  5f7t    45 non-null     str
 43  k2v7    45 non-null     str
 44  6g6y    45 non-null     str
 45  9j3o    45 non-null     str
 46  8i4i    45 non-null     str
 47  7h5u    45 non-null     str
 48  h8s1    45 non-null     str
 49  i9t9    45 non-null     str
 50  j1u8    45 non-null     str
 51  m8g5    45 non-null     str
 52  p9i3    45 non-null     str
 53  g9j5    45 non-null     str
 54  h7j3    45 non-null     str
 55  y8c3    45 non-null     str
 56  g7r2    45 non-null     str
 57  f6q3    45 non-null     str
 58  e5p4    45 non-null     str
 59  d4n6    45 non-null     str
 60  c3m7    45 non-null     str
 61  b2l8    45 non-null     str
 62  a1k9    45 non-null     str
 63  t6v9    45 non-null     str
 64  b9w0    45 non-null     str
dtypes: str(65)
memory usage: 23.2+ KB
None
==================================================

,hh2e,wfsl,37ir,hvpa,ql3b,r0a3,qx2o,wssm,ctzy,uyrl,...,y8c3,g7r2,f6q3,e5p4,d4n6,c3m7,b2l8,a1k9,t6v9,b9w0
Tasks,,,,,,,,,,,,,,,,,,,,,
Breathing_relax,6,6,9,9,10,10,9,8,9,9,...,9,8,9,10,5,4,8,7,5,8
Breathing_stress,5,4,2,1,1,0,2,0,0,1,...,1,0,1,3,2,6,1,5,5,2
Breathing_valence,NaN,8,5,7,5,8,8,6,7,6,...,5,7,7,8,5,8,7,6,6,7
Breathing_arousal,NaN,3,3,8,2,1,2,1,7,5,...,7,5,1,3,4,7,8,8,3,8
Video1_relax,8,6,3,7,10,10,9,5,4,7,...,8,8,9,8,2,2,2,7,7,5

In [166]:
self_assessments.tail()

,hh2e,wfsl,37ir,hvpa,ql3b,r0a3,qx2o,wssm,ctzy,uyrl,...,y8c3,g7r2,f6q3,e5p4,d4n6,c3m7,b2l8,a1k9,t6v9,b9w0
Tasks,,,,,,,,,,,,,,,,,,,,,
Relax_relax,6,NaN,7,6,10,10,4,7,9,8,...,9,8,9,8,5,7,6,8,3,2
Relax_stress,6,NaN,1,2,0,1,5,0,1,2,...,0,0,1,2,3,5,5,3,3,5
Relax_valence,NaN,NaN,7,6,8,6,5,7,5,5,...,6,5,8,7,5,6,7,8,5,5
Relax_arousal,NaN,NaN,6,5,8,2,3,0,1,4,...,4,2,1,3,3,7,6,5,0,4
Most_stressful,Counting2,Counting2,Speaking,Reading,Speaking,Counting3,Speaking,Speaking,Math,Speaking,...,Counting2,Counting3,Stroop,Counting2,Counting1,Stroop,Counting2,Counting2,Counting2,Counting2

In [167]:
# Store last row in a variable and drop it from primary dataset
most_stressfull = self_assessments.tail(1)
# print(most_stressfull)

df = self_assessments
df.drop(df.tail(1).index, inplace=True)

In [168]:
df.tail()

,hh2e,wfsl,37ir,hvpa,ql3b,r0a3,qx2o,wssm,ctzy,uyrl,...,y8c3,g7r2,f6q3,e5p4,d4n6,c3m7,b2l8,a1k9,t6v9,b9w0
Tasks,,,,,,,,,,,,,,,,,,,,,
Counting3_arousal,NaN,6,8,8,10,6,6,6,9,6,...,5,4,3,5,6,5,6,7,8,8
Relax_relax,6,NaN,7,6,10,10,4,7,9,8,...,9,8,9,8,5,7,6,8,3,2
Relax_stress,6,NaN,1,2,0,1,5,0,1,2,...,0,0,1,2,3,5,5,3,3,5
Relax_valence,NaN,NaN,7,6,8,6,5,7,5,5,...,6,5,8,7,5,6,7,8,5,5
Relax_arousal,NaN,NaN,6,5,8,2,3,0,1,4,...,4,2,1,3,3,7,6,5,0,4

In [169]:
# function to map subject/task pair values to binary class for "relax", "valence", "arousal"
# 0-5 -> 0 (relax) and 6-10 -> 1 (not relax)
def map_to_binary(value):
    if pd.isna(value):
        return pd.NA
    value = float(value)
    return 0 if value <= 5 else 1

In [170]:
# split each row label "<Task>_<measure>" into (Task, measure)
# e.g. "Breathing_relax" -> ("Breathing", "relax")
df["__task"], df["__measure"]  = zip(*df.index.map(lambda x:x .rsplit("_", 1)))

# print(df["__task"]), print(df["__measure"])

In [171]:
df.head()

,hh2e,wfsl,37ir,hvpa,ql3b,r0a3,qx2o,wssm,ctzy,uyrl,...,f6q3,e5p4,d4n6,c3m7,b2l8,a1k9,t6v9,b9w0,__task,__measure
Tasks,,,,,,,,,,,,,,,,,,,,,
Breathing_relax,6,6,9,9,10,10,9,8,9,9,...,9,10,5,4,8,7,5,8,Breathing,relax
Breathing_stress,5,4,2,1,1,0,2,0,0,1,...,1,3,2,6,1,5,5,2,Breathing,stress
Breathing_valence,NaN,8,5,7,5,8,8,6,7,6,...,7,8,5,8,7,6,6,7,Breathing,valence
Breathing_arousal,NaN,3,3,8,2,1,2,1,7,5,...,1,3,4,7,8,8,3,8,Breathing,arousal
Video1_relax,8,6,3,7,10,10,9,5,4,7,...,9,8,2,2,2,7,7,5,Video1,relax

In [175]:
rows = []
for subject in df.columns[:-2]: # exclude columns __task and __measure
    for task in df["__task"].unique():
        sub_df = df[df["__task"] == task]

        relax_val = sub_df.loc[sub_df["__measure"] == "relax", subject]
        valence_val = sub_df.loc[sub_df["__measure"] == "valence", subject]
        arousal_val = sub_df.loc[sub_df["__measure"] == "arousal", subject]

        rows.append({
            "subject_task": f"{subject}_{task}",
            "binary_relax": map_to_binary(relax_val.iloc[0]) if not relax_val.empty else pd.NA,
            "binary_valence": map_to_binary(valence_val.iloc[0]) if not valence_val.empty else pd.NA,
            "binary_arousal": map_to_binary(arousal_val.iloc[0]) if not arousal_val.empty else pd.NA,
        })

result = pd.DataFrame(rows)
result.head()

     subject_task binary_relax binary_valence binary_arousal
0  hh2e_Breathing            1           <NA>           <NA>
1     hh2e_Video1            1           <NA>           <NA>
2     hh2e_Video2            1           <NA>           <NA>
3  hh2e_Counting1            1           <NA>           <NA>
4  hh2e_Counting2            0           <NA>           <NA>